services:
  - type: web
    name: notiva
    env: python
    buildCommand: "pip install -r requirements.txt && python -m flask db upgrade"
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_APP
        value: "wsgi:app"
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: notiva-db
          property: connectionString

databases:
  - name: notiva-db
    databaseName: notiva_db
    user: notiva_user
    plan: free
