services:
  - type: web
    name: notiva
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: notiva-db
          property: connectionString

databases:
  - name: notiva-db
    databaseName: notiva_db
    user: notiva_user
    plan: free
