services:
  - type: web
    name: notiva
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    disk:
      name: sqlite
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
    envVars:
      - key: FLASK_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///instance/notiva.db 