services:
  - type: web
    name: notiva
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_AkeGQ5IBMNy4dep-withered-hill-aing4uwt-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      - key: OPENAI_API_KEY
        sync: false
