services:
  - type: web
    name: notiva
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_APP
        value: "wsgi:app"
      - key: FLASK_ENV
        value: production
      - key: FLASK_CONFIG
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_AkeGQ5IBMNy4dep-withered-hill-aing4uwt-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      - key: OPENAI_API_KEY
